# Generated by Django 5.2.10 on 2026-01-20 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_roadmapbundle'),
        ('payments', '0002_coupon_payment_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.roadmapbundle'),
        ),
        migrations.AddField(
            model_name='payment',
            name='roadmap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.roadmap'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscriptionplan'),
        ),
    ]
