# Generated by Django 5.2.10 on 2026-01-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_phone'),
        ('payments', '0003_payment_bundle_payment_roadmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='valid_for_bundles',
            field=models.ManyToManyField(blank=True, to='core.roadmapbundle'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_for_plans',
            field=models.ManyToManyField(blank=True, to='payments.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_for_roadmaps',
            field=models.ManyToManyField(blank=True, to='core.roadmap'),
        ),
    ]
