# Generated by Django 5.2.10 on 2026-02-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_coupon_valid_for_bundles_coupon_valid_for_plans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Is this a free trial subscription?'),
        ),
    ]
