# Generated by Django 5.2.10 on 2026-02-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_usersubscription_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_default_trial',
            field=models.BooleanField(default=False, help_text='If checked, new users will get this plan automatically.', verbose_name='Is Default Free Trial?'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_type',
            field=models.CharField(choices=[('trial', 'Free Trial'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], max_length=20),
        ),
    ]
