# Generated by Django 5.2.10 on 2026-01-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_roadmapbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF resource for this roadmap', null=True, upload_to='roadmaps/pdfs/'),
        ),
    ]
