# Generated by Django 5.2.10 on 2026-01-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_roadmap_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='future_goals',
            field=models.TextField(blank=True, help_text='What are your career aspirations?', verbose_name='Future Goals'),
        ),
        migrations.AddField(
            model_name='user',
            name='github_profile',
            field=models.URLField(blank=True, verbose_name='GitHub Profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_profile',
            field=models.URLField(blank=True, verbose_name='LinkedIn Profile'),
        ),
    ]
