# Generated by Django 5.2.10 on 2026-02-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_broadcastemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Your Learning Progress Update 🚀', max_length=200)),
                ('intro_message', models.TextField(blank=True, help_text='Optional custom message at the top', verbose_name='Intro Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
