# Generated by Django 5.2.10 on 2026-02-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_giveaway_giveawayparticipation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_free_trial', models.BooleanField(default=False, verbose_name='Enable Free Trial for New Users')),
                ('trial_duration_days', models.PositiveIntegerField(default=7, verbose_name='Trial Duration (Days)')),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.AddField(
            model_name='weeklygoal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
