# Generated by Django 5.2.10 on 2026-02-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_globalsetting_weeklygoal_is_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSetting',
        ),
    ]
