# Generated by Django 5.2.10 on 2026-02-16 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_event', models.CharField(choices=[('page_view', 'Page View'), ('time_on_page', 'Time on Page (sec)'), ('click', 'Element Click'), ('idle', 'User Idle'), ('exit_intent', 'Exit Intent')], max_length=20)),
                ('trigger_condition', models.JSONField(default=dict, help_text='{"path": "/pricing", "value": 30}')),
                ('action_type', models.CharField(choices=[('message', 'Show Message'), ('overlay', 'Show Overlay'), ('redirect', 'Redirect')], default='message', max_length=20)),
                ('message_content', models.TextField()),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('cta_link', models.CharField(blank=True, max_length=200)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('page_views', models.JSONField(default=dict)),
                ('interests', models.JSONField(default=dict)),
                ('is_bounced', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
