
import os
import django
import sys

# Setup settings
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'roadmap99.settings')
django.setup()

from core.models import Roadmap, Stage, Topic, RoadmapCategory
from django.utils.text import slugify

def create_roadmap():
    print("🚀 Creating Frontend Basics Roadmap...")

    # 1. Get or Create Category
    category, _ = RoadmapCategory.objects.get_or_create(
        name="Development",
        defaults={
            'slug': 'development',
            'description': 'Software Development Roadmaps',
            'icon': 'fa-code',
            'color': '#3b82f6'
        }
    )

    # 2. Create Roadmap
    title = "Frontend Basics (HTML/CSS/JS)"
    slug = "frontend-basics"
    
    # Check if exists
    if Roadmap.objects.filter(slug=slug).exists():
        print(f"⚠️ Roadmap '{title}' already exists. Skipping.")
        return

    roadmap = Roadmap.objects.create(
        title=title,
        slug=slug,
        description="A professional Frontend Basics roadmap for CSE / BTech students, covering HTML, CSS, and JavaScript, starting from absolute basics and building strong industry-ready foundations.",
        short_description="Master HTML, CSS & JavaScript from scratch.",
        category=category,
        difficulty='beginner',
        is_premium=False, # Free as requested for Stage 1, making entire roadmap free? 
                          # User said "Stage 1: Web Foundations (Basic – FREE)". Only stage 1 is explicitly free.
                          # But "Avoid frameworks... suitable for roadmap-based learning platform".
                          # Let's verify stage-level premium.
                          # Stage model has is_free boolean. Roadmap is premium if ANY stage is not free.
        price=499, # Set a placeholder price if it becomes premium later
        estimated_hours=40,
        is_active=True,
        is_featured=True
    )

    # 3. Create Stages & Topics
    stages_data = [
        {
            "title": "Web Foundations",
            "description": "Understand how the web works",
            "is_free": True,
            "order": 1,
            "topics": [
                {
                    "title": "What is Frontend Development?",
                    "content": """
**Goal:** Understand the role of a Frontend Developer.

*   **Frontend vs Backend:** Frontend is what users see and interact with (UI). Backend is data and logic.
*   **The Big Three:** 
    *   **HTML:** Structure (The skeleton).
    *   **CSS:** Style (The clothes/makeup).
    *   **JavaScript:** Logic (The muscles/brains).
*   **Role in Industry:** Converting designs (Figma) into working code that runs in a browser.
                    """,
                    "duration": 15
                },
                {
                    "title": "How Browsers Work",
                    "content": """
**Goal:** Learn how a browser renders pages.

*   **DNS Resolution:** How `google.com` becomes an IP address.
*   **HTTP Request/Response:** The conversation between Client (Browser) and Server.
*   **Rendering Engine:** How code becomes pixels (Parsing HTML -> DOM Tree -> Layout -> Paint).
*   **Assets:** How the browser fetches images, CSS, and JS in parallel.
                    """,
                    "duration": 20
                },
                {
                    "title": "Client-Server Architecture",
                    "content": """
**Goal:** High-level understanding of data flow.

*   **Client:** The user's device (Browser, Mobile App).
*   **Server:** The computer storing the website/database.
*   **API (Application Programming Interface):** The messenger between Client and Server.
*   **Static vs Dynamic:** Static sites (HTML files) vs Dynamic (generated by logic like Python/Node.js).
                    """,
                    "duration": 20
                }
            ]
        },
        {
            "title": "HTML – Structure of the Web",
            "description": "Build clean, meaningful page structure",
            "is_free": False, # Implicitly paid past stage 1? Let's make it affordable or following standard content.
            "order": 2,
            "topics": [
                {
                    "title": "HTML Basics & Document Structure",
                    "content": """
**Goal:** Write a valid HTML5 document.

*   **Tags & Elements:** Opening tag, closing tag, content (e.g., `<p>Text</p>`).
*   **Attributes:** Providing extra info (e.g., `class`, `id`, `src`).
*   **The Skeleton:** `<!DOCTYPE html>`, `<html>`, `<head>`, `<body>`.
*   **Meta Tags:** Why `viewport` and `charset` are critical for mobile.
                    """,
                    "duration": 25
                },
                {
                    "title": "Semantic HTML",
                    "content": """
**Goal:** Write meaningful code, not just `<div>` soup.

*   **Why Semantics Matter:** SEO (Google understanding your site) and Accessibility (Screen readers).
*   **Key Tags:** `<header>`, `<nav>`, `<main>`, `<article>`, `<section>`, `<footer>`, `<aside>`.
*   **When to use what:** Don't use a `<div>` for a button. Use `<button>`.
                    """,
                    "duration": 30
                },
                {
                    "title": "Forms & Inputs",
                    "content": """
**Goal:** Collect user data correctly.

*   **The `<form>` tag:** Action and Method (GET vs POST).
*   **Input Types:** `text`, `password`, `email`, `number`, `checkbox`, `radio`.
*   **Labels:** Why connecting `<label for="id">` is mandatory for accessibility.
*   **Validation:** Native attributes like `required`, `min`, `max`, `pattern`.
                    """,
                    "duration": 35
                },
                {
                    "title": "Accessibility (A11y) Basics",
                    "content": """
**Goal:** Make the web for everyone.

*   **Alt Text:** Describing images for blind users using `alt=""`.
*   **Keyboard Navigation:** Ensuring all interactive elements can be reached with `Tab`.
*   **Heading Hierarchy:** `h1` through `h6` order matters (don't skip levels for styling).
                    """,
                    "duration": 20
                }
            ]
        },
        {
            "title": "CSS – Styling & Layout",
            "description": "Design responsive, usable interfaces",
            "is_free": False,
            "order": 3,
            "topics": [
                {
                    "title": "CSS Fundamentals",
                    "content": """
**Goal:** Applying styles to HTML.

*   **Selectors:** Class (`.`), ID (`#`), Element (`div`), and combinators (`>`).
*   **Specificity:** Who wins when rules conflict? (ID > Class > Tag).
*   **The Cascade:** How order affects styling.
*   **Units:** Absolute (`px`) vs Relative (`rem`, `em`, `%`, `vh/vw`). **Always use `rem` for readability.**
                    """,
                    "duration": 40
                },
                {
                    "title": "The Box Model",
                    "content": """
**Goal:** Understanding size and spacing.

*   **Components:** Content, Padding (Inside), Border, Margin (Outside).
*   **`box-sizing: border-box`:** The most important CSS reset. It ensures padding doesn't increase element width.
*   **Display Properties:** `block` vs `inline` vs `inline-block` vs `none`.
                    """,
                    "duration": 30
                },
                {
                    "title": "Modern Layouts: Flexbox & Grid",
                    "content": """
**Goal:** Positioning elements without hacks.

*   **Flexbox (1D):** Aligning items in a row or column.
    *   `justify-content` (Main Axis).
    *   `align-items` (Cross Axis).
    *   `flex-wrap`.
*   **Grid (2D):** Creating complex layouts (Rows + Columns).
    *   `grid-template-columns`.
    *   `gap`.
*   **When to use which:** Flexbox for components (navbars), Grid for overall page layout.
                    """,
                    "duration": 60
                },
                {
                    "title": "Responsive Design Basics",
                    "content": """
**Goal:** Making sites look good on Mobile, Tablet, and Desktop.

*   **The Viewport Meta Tag:** Essential for mobile scaling.
*   **Media Queries:** `@media (min-width: 768px) { ... }`.
*   **Mobile-First Approach:** Style for mobile first, then add complexity for desktop.
                    """,
                    "duration": 45
                }
            ]
        },
        {
            "title": "JavaScript – Behavior & Logic",
            "description": "Make websites interactive",
            "is_free": False,
            "order": 4,
            "topics": [
                {
                    "title": "JS Fundamentals",
                    "content": """
**Goal:** Programming basics in JS context.

*   **Variables:** `let` vs `const` (Avoid `var`).
*   **Data Types:** String, Number, Boolean, Array, Object, null/undefined.
*   **Functions:** Arrow functions (`() => {}`) vs Traditional.
*   **Control Flow:** `if/else`, loops (`map`, `forEach`, `filter` -> prefer these over `for` loops).
                    """,
                    "duration": 60
                },
                {
                    "title": "DOM Manipulation",
                    "content": """
**Goal:** Changing HTML with JavaScript.

*   **Selection:** `document.querySelector()` and `querySelectorAll()`.
*   **Modification:** `element.textContent`, `element.style`, `element.classList.add/remove`.
*   **Creation:** `document.createElement()` and `appendChild()`.
                    """,
                    "duration": 50
                },
                {
                    "title": "Events & Interactions",
                    "content": """
**Goal:** Responding to user actions.

*   **Event Listeners:** `addEventListener('click', callback)`.
*   **Common Events:** `click`, `submit`, `input`, `scroll`.
*   **Event Bubbling & Capturing:** How events travel through the DOM.
*   **Delegation:** Adding one listener to a parent instead of 100 children (performance).
                    """,
                    "duration": 50
                },
                {
                    "title": "Async Concepts (High Level)",
                    "content": """
**Goal:** Handling tasks that take time (like fetching data).

*   **The Call Stack:** JS is single-threaded.
*   **Promises:** `.then()` and `.catch()`.
*   **Async/Await:** Writing async code that looks synchronous (modern standard).
                    """,
                    "duration": 45
                }
            ]
        },
        {
            "title": "Frontend Foundations for Industry",
            "description": "Be ready for real frontend projects",
            "is_free": False,
            "order": 5,
            "topics": [
                {
                    "title": "Connecting with APIs",
                    "content": """
**Goal:** Fetching real data.

*   **Fetch API:** `fetch('https://api.example.com/data')`.
*   **JSON:** Parsing response data `await response.json()`.
*   **HTTP Methods:** GET (Read), POST (Create), PUT (Update), DELETE (Remove).
*   **Error Handling:** `try...catch` blocks for network failures.
                    """,
                    "duration": 50
                },
                {
                    "title": "Browser Storage",
                    "content": """
**Goal:** Remembering user data.

*   **LocalStorage:** Persistent data (Theme preference, Auth token).
*   **SessionStorage:** Temporary data (Tab specific).
*   **Cookies:** basics for authentication.
                    """,
                    "duration": 30
                },
                {
                    "title": "Debugging",
                    "content": """
**Goal:** Fixing broken code.

*   **Console:** `console.log`, `console.table`, `console.error`.
*   **DevTools:** Inspect Element, Network Tab (checking API calls), Application Tab (Storage).
*   **Debugger:** Using breakpoints instead of printing logs.
                    """,
                    "duration": 40
                },
                {
                    "title": "Next Steps: Ready for React",
                    "content": """
**Goal:** Where to go from here?

*   **ES6+ Features:** Destructuring, Spread Operator, Modules (import/export).
*   **Why Frameworks?** Handling complex state that vanilla JS struggles with.
*   **Recommendation:** Start the **React JS Advanced** roadmap next.
                    """,
                    "duration": 20
                }
            ]
        }
    ]

    for stage_data in stages_data:
        stage = Stage.objects.create(
            roadmap=roadmap,
            title=stage_data['title'],
            description=stage_data['description'],
            is_free=stage_data['is_free'],
            order=stage_data['order']
        )
        
        for i, topic_data in enumerate(stage_data['topics'], 1):
            Topic.objects.create(
                stage=stage,
                title=topic_data['title'],
                content=topic_data['content'],
                content_type='text',
                order=i,
                duration_minutes=topic_data['duration']
            )
            
    # Update Stats
    roadmap.update_stats()
    print(f"✅ Successfully created Roadmap: {roadmap.title}")

if __name__ == "__main__":
    create_roadmap()
